import { Tournament, Table, Seat, Round } from '../types';

export const mockTournaments: Tournament[] = [
  {
    id: '1',
    name: '$10 BTC Turbo',
    asset: 'BTC',
    buyIn: 10,
    currency: 'POINTS',
    guaranteedPrize: 500,
    maxEntrants: 100,
    currentEntrants: 47,
    levelDuration: 15,
    status: 'REGISTERING',
    startTime: Date.now() + 300000,
    currentLevel: 0,
    playersRemaining: 0,
    tables: [],
  },
  {
    id: '2',
    name: '$50 ETH Regular',
    asset: 'ETH',
    buyIn: 50,
    currency: 'POINTS',
    guaranteedPrize: 2500,
    maxEntrants: 200,
    currentEntrants: 123,
    levelDuration: 30,
    status: 'RUNNING',
    startTime: Date.now() - 600000,
    currentLevel: 3,
    playersRemaining: 78,
    tables: [],
  },
  {
    id: '3',
    name: '$100 BTC Deep Stack Sunday Special',
    asset: 'BTC',
    buyIn: 100,
    currency: 'POINTS',
    guaranteedPrize: 10000,
    maxEntrants: 500,
    currentEntrants: 342,
    levelDuration: 60,
    status: 'LATE_REG',
    startTime: Date.now() - 1800000,
    currentLevel: 2,
    playersRemaining: 289,
    tables: [],
  },
  {
    id: '4',
    name: '$25 BTC Turbo',
    asset: 'BTC',
    buyIn: 25,
    currency: 'POINTS',
    guaranteedPrize: 1000,
    maxEntrants: 150,
    currentEntrants: 89,
    levelDuration: 15,
    status: 'REGISTERING',
    startTime: Date.now() + 600000,
    currentLevel: 0,
    playersRemaining: 0,
    tables: [],
  },
  {
    id: '5',
    name: '$5 ETH Micro Turbo',
    asset: 'ETH',
    buyIn: 5,
    currency: 'POINTS',
    guaranteedPrize: 200,
    maxEntrants: 50,
    currentEntrants: 34,
    levelDuration: 15,
    status: 'RUNNING',
    startTime: Date.now() - 300000,
    currentLevel: 1,
    playersRemaining: 28,
    tables: [],
  },
];

export const mockSeats: Seat[] = [
  {
    position: 0,
    playerId: 'player1',
    playerName: 'CryptoKing',
    playerAvatar: null,
    status: 'ACTIVE',
    currentPrediction: null,
    isCurrentPlayer: false,
    strikes: 0,
    maxStrikes: 3,
  },
  {
    position: 1,
    playerId: 'player2',
    playerName: 'DiamondHands',
    playerAvatar: null,
    status: 'ACTIVE',
    currentPrediction: null,
    isCurrentPlayer: false,
    strikes: 1,
    maxStrikes: 3,
  },
  {
    position: 2,
    playerId: 'player3',
    playerName: 'MoonShot',
    playerAvatar: null,
    status: 'ACTIVE',
    currentPrediction: null,
    isCurrentPlayer: false,
    strikes: 2,
    maxStrikes: 3,
  },
  {
    position: 3,
    playerId: 'player4',
    playerName: 'ChartMaster',
    playerAvatar: null,
    status: 'LOCKED_IN',
    currentPrediction: 50250,
    isCurrentPlayer: false,
    strikes: 0,
    maxStrikes: 3,
  },
  {
    position: 4,
    playerId: 'player5',
    playerName: 'BullRun',
    playerAvatar: null,
    status: 'ACTIVE',
    currentPrediction: null,
    isCurrentPlayer: false,
    strikes: 1,
    maxStrikes: 3,
  },
  {
    position: 5,
    playerId: 'player6',
    playerName: 'Satoshi2.0',
    playerAvatar: null,
    status: 'LOCKED_IN',
    currentPrediction: 49900,
    isCurrentPlayer: false,
    strikes: 0,
    maxStrikes: 3,
  },
  {
    position: 6,
    playerId: 'player7',
    playerName: 'HODLGANG',
    playerAvatar: null,
    status: 'ACTIVE',
    currentPrediction: null,
    isCurrentPlayer: false,
    strikes: 2,
    maxStrikes: 3,
  },
  {
    position: 7,
    playerId: 'currentPlayer',
    playerName: 'You',
    playerAvatar: null,
    status: 'ACTIVE',
    currentPrediction: null,
    isCurrentPlayer: true,
    strikes: 0,
    maxStrikes: 3,
  },
  {
    position: 8,
    playerId: null,
    playerName: null,
    playerAvatar: null,
    status: 'EMPTY',
    currentPrediction: null,
    isCurrentPlayer: false,
    strikes: 0,
    maxStrikes: 3,
  },
];

const now = Date.now();
export const mockRound: Round = {
  id: 'round1',
  tableId: 'table1',
  levelNumber: 1,
  asset: 'BTC',
  startPrice: 49800,
  roundStartTime: now,
  predictionWindowStart: now,
  predictionChangeDeadline: now + 4 * 60 * 1000, // +4 minutes
  predictionLockDeadline: now + 5 * 60 * 1000, // +5 minutes
  resolutionTime: now + 30 * 60 * 1000, // +30 minutes
  actualEndPrice: null,
  predictions: [],
  eliminations: [],
};

export const mockTable: Table = {
  id: 'table1',
  tournamentId: '1',
  seats: mockSeats,
  currentRound: mockRound,
  status: 'PREDICTIONS_OPEN',
};

export const initializeMockData = () => {
  return {
    tournaments: mockTournaments,
    table: mockTable,
  };
};
